<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <Description>Mediana Kafka transport provider: topics, retry-topics, partition ordering.</Description>
    <IsPackable>true</IsPackable>
    <PackageId>Mediana.Kafka</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mediana.Transport.Abstractions\Mediana.Transport.Abstractions.csproj" />
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>
</Project>
