<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Mediana\Mediana.csproj" />
    <ProjectReference Include="..\..\src\Mediana.Transport.Abstractions\Mediana.Transport.Abstractions.csproj" />
  </ItemGroup>
</Project>
